// src/constants/products.js
export const products = [
  {
    id: 1,
    image: "src/assets/images/butterPecan.png",
    title: "Butter Pecan",
    description: "Crunchy pecan biscotti with a rich, buttery flavor.",
    type: "biscotti",
    ingredients: [
      "Enriched flour",
      "Butter",
      "Pecans",
      "Sugar",
      "Eggs",
      "Vanilla extract",
      "Salt",
      "Baking powder",
    ],
    pairings: ["Espresso", "Latte", "Hot Chocolate"],
  },
  {
    id: 2,
    image: "src/assets/images/cayenneSnickerdoodle.png",
    title: "Cayenne Snickerdoodle",
    description: "Classic soft cookie with a hint of cinnamon spice and a cayenne kick.",
    type: "cookie",
    ingredients: [
      "Enriched flour",
      "Butter",
      "Sugar",
      "Cinnamon",
      "Eggs",
      "Cayenne pepper",
      "Vanilla extract",
      "Salt",
      "Baking soda",
    ],
    pairings: ["Chai Tea", "Iced Latte", "Hot Chocolate"],
  },
  {
    id: 3,
    image: "src/assets/images/chickenWaffle.png",
    title: "Chicken Waffle",
    description: "Savory cookie with sweet maple and a hint of crispy chicken flavor.",
    type: "cookie",
    ingredients: [
      "Enriched flour",
      "Butter",
      "Maple syrup",
      "Sugar",
      "Eggs",
      "Chicken seasoning",
      "Salt",
      "Baking powder",
    ],
    pairings: ["Sweet Tea", "Cold Brew", "Maple Latte"],
  },
  {
    id: 4,
    image: "src/assets/images/chocolateChipCrunch.png",
    title: "Chocolate Chip Crunch",
    description: "A soft cookie loaded with chocolate chips and a satisfying crunch.",
    type: "cookie",
    ingredients: [
      "Enriched flour",
      "Butter",
      "Chocolate chips",
      "Sugar",
      "Eggs",
      "Vanilla extract",
      "Baking soda",
      "Salt",
    ],
    pairings: ["Cappuccino", "Mocha", "Milk"],
  },
  {
    id: 5,
    image: "src/assets/images/cookiesNCream.png",
    title: "Cookies N' Cream",
    description: "Crunchy biscotti with chunks of chocolate cookie and creamy white chocolate.",
    type: "biscotti",
    ingredients: [
      "Enriched flour",
      "White chocolate",
      "Chocolate cookie pieces",
      "Sugar",
      "Eggs",
      "Butter",
      "Vanilla extract",
      "Salt",
      "Baking powder",
    ],
    pairings: ["Americano", "Milkshake", "Hot Cocoa"],
  },
  {
    id: 6,
    image: "src/assets/images/cosmicChocolate.png",
    title: "Cosmic Chocolate",
    description: "Soft chocolate cookie with a sprinkle of cosmic-colored candies.",
    type: "cookie",
    ingredients: [
      "Enriched flour",
      "Butter",
      "Sugar",
      "Cocoa powder",
      "Chocolate candies",
      "Eggs",
      "Salt",
      "Baking soda",
    ],
    pairings: ["Cold Brew", "Espresso", "Chocolate Milk"],
  },
  {
    id: 7,
    image: "src/assets/images/funfetti.png",
    title: "Funfetti",
    description: "Colorful, soft cookie bursting with funfetti sprinkles.",
    type: "cookie",
    ingredients: [
      "Enriched flour",
      "Butter",
      "Sugar",
      "Rainbow sprinkles",
      "Eggs",
      "Vanilla extract",
      "Salt",
      "Baking soda",
    ],
    pairings: ["Iced Tea", "Lemonade", "Vanilla Latte"],
  },
  {
    id: 8,
    image: "src/assets/images/lemonPoppy.png",
    title: "Lemon Poppy",
    description: "Crisp biscotti with a bright lemon flavor and poppyseed crunch.",
    type: "biscotti",
    ingredients: [
      "Enriched flour",
      "Butter",
      "Sugar",
      "Lemon zest",
      "Poppy seeds",
      "Eggs",
      "Salt",
      "Baking powder",
    ],
    pairings: ["Green Tea", "Lemonade", "Chamomile Tea"],
  },
  {
    id: 9,
    image: "src/assets/images/saltedChocolate.png",
    title: "Salted Chocolate",
    description: "Decadent chocolate cookie sprinkled with sea salt for added depth.",
    type: "cookie",
    ingredients: [
      "Enriched flour",
      "Butter",
      "Dark chocolate",
      "Sugar",
      "Eggs",
      "Cocoa powder",
      "Sea salt",
      "Baking soda",
    ],
    pairings: ["Red Wine", "Espresso", "Café au Lait"],
  },
  {
    id: 10,
    image: "src/assets/images/thickMint.png",
    title: "Thick Mint",
    description: "Dense chocolate cookie with a cool minty freshness.",
    type: "cookie",
    ingredients: [
      "Enriched flour",
      "Butter",
      "Sugar",
      "Mint extract",
      "Cocoa powder",
      "Dark chocolate chips",
      "Eggs",
      "Salt",
      "Baking soda",
    ],
    pairings: ["Mint Tea", "Hot Chocolate", "Vanilla Milkshake"],
  },
];
